LPD-70417 Use MemoryRouter instead of RouteWrapper
RouteWrapper was also causing an error:
TypeError: Cannot read properties of undefined (reading 'pathname')

MemoryRouter seems to be the correct use of using a Router in tests and makes it simpler too.