LPD-17094 Set the parent ClassLoader to the ClassLoader#getSystemClassLoader for the instances of URLClassLoader into the NewEnvTestRule to avoid the java.lang.NoClassDefFoundError: java/sql/SQLException when running on jdk21. The issue is that in Java 9 and later, the behavior of a ClassLoader whose parent ClassLoader is null is different than that of Java 8. In java 8, It expects that a null parent ClassLoader end up giving access to everything available to the JVM but in Java 9 and later, it gets only the core packages, like java.lang but not include the java.sql for example. See references here, https://bugs.openjdk.org/browse/JDK-8161269 and https://docs.oracle.com/javase/9/docs/api/java/lang/ClassLoader.html#builtinLoaders